name: Publish zsh-setup.sh

on:
  push:
    branches:
      - main  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zsh-setup.sh
          path: zsh-setup.sh
